// react-example/src/App.tsx
import { DBButton } from "@db-ux/react-core-components";

const App = () => {
  return (
    <main>
      <div
        data-density="functional"
        className="db-color-informational container-with-padding"
      >
        <h1>db-ux-functional</h1>
        <p>Use this as default for enterprise apps</p>
        <DBButton icon="plus">Test</DBButton>
      </div>
      <div
        data-density="regular"
        className="db-color-successful container-with-padding"
      >
        <h1>db-ux-regular</h1>
        <p>Use this as default for consumer apps</p>
        <DBButton icon="plus">Test</DBButton>
      </div>
      <div
        data-density="expressive"
        className="db-color-successful db-bg-color-basic-level-2 container-with-padding"
      >
        <h1>db-ux-expressive</h1>
        <p>Use this as default for marketing apps</p>
        <DBButton icon="plus">Test</DBButton>
      </div>
    </main>
  );
};

export default App;

// angular17-example/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { DBButton } from '@db-ux/ngx-core-components';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, DBButton],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  title = 'angular17-example';
}

<main>
  <div
    data-density="functional"
    class="db-color-informational container-with-padding"
  >
    <h1>db-ux-functional</h1>
    <p>Use this as default for enterprise apps</p>
    <db-button icon="plus">Test</db-button>
  </div>
  <div
    data-density="regular"
    class="db-color-successful container-with-padding"
  >
    <h1>db-ux-regular</h1>
    <p>Use this as default for consumer apps</p>
    <db-button icon="plus">Test</db-button>
  </div>
  <div
    data-density="expressive"
    class="db-color-successful db-bg-color-basic-level-2 container-with-padding"
  >
    <h1>db-ux-expressive</h1>
    <p>Use this as default for marketing apps</p>
    <db-button icon="plus">Test</db-button>
  </div>
</main>
